### ISSUE TITLE
Dodanie pobierania postów z fanpage na facebooku i umieszczanie ich na stronie głównej.

### ISSUE THREAD

**Issue by ZielinskyArts** [Adexion/GameSitesSellIssue#10]

**Comment by Adexion** [comment]
https://developers.facebook.com/docs/graph-api/reference/page/feed/|
GET https://graph.facebook.com/v2.3/me/posts?fields=message,picture,link,likes&access_token={page_access_token}
Metoda pozwala na pobranie ostatniego postu z fb. 
Czy chcemy taką funkcjonalność?
Jak miałaby ona wyglądać?
