### ISSUE TITLE
Możliwość edytowania każdego tekstu na stronie głównej

### ISSUE THREAD

**Issue by ZielinskyArts** [Adexion/GameSitesSellIssue#11]

**Comment by opiepl** [comment]
Cześć, większość tekstów można modyfikować. Które dokładnie teksty chciałbyś jeszcze modyfikować?

**Comment by Adexion** [comment]
po rozmowie z @ZielinskyArts dodano możliwość edycji tekstu gildyjnego.
Na produkcji
