### ISSUE TITLE
Dodanie paska ilości w zakupach

### ISSUE THREAD

**Issue by Piechuuu** [Adexion/GameSitesSellIssue#37]
![image](https://user-images.githubusercontent.com/46606720/157336844-d7f19747-35a1-4114-b0e1-53c1d7d3ed2d.png)
dodanie tutaj opcji ilość żeby na stronie jeśli chce ktoś coś zakupić bedzie przeciągał sie taki pasek od 1 do ustalonej liczby w konfiguracji
ale żeby tam był jakiś boolean w tej konfiguracji czy jest tutaj potrzebna opcja ilości i no jeśli ktoś se chce zakupić jakieś magiczne skrzynki to wybiera sobie ile przeciągając na pasku w sklepie i fajnie jakbyście to szybko zrobili bo bardzo potrzebne żeby nie dodawać miliona usług typu case x2, case x4 itd mam nadzieje że wiecie o co mi chodzi

**Comment by Adexion** [comment]
na produkcji
