### ISSUE TITLE
Prośba o dodanie do rankingów/banów mongodb

### ISSUE THREAD

**Issue by Piechuuu** [Adexion/GameSitesSellIssue#39]
Fajnie gdyby to było ponieważ dużo programistów którzy robią serwery używają teraz mongodb znam ich od groma i jest coś przydatnego opcje np:

ip(mongodb)
port(mongodb)
databaseName(mongodb)

collection(kolekcja w bazie)
dataSearch(czyli wpisanie nazwy fielda z kolekcji w bazie np: nickName, points) zwraca nick gracza z fielda
mozna dodac jakies info ze pierwszy field w dataSearch to nazwa gracz a po przecinku punkty gracz
dataSearchType(POINTS, KILLS, DEATHS, ETC)

bardzo przydatne !!

**Comment by Adexion** [comment]
na produkcji
