### ISSUE TITLE
Konsola Rcon

### ISSUE THREAD

**Issue by likasop** [Adexion/GameSitesSellIssue#4]
Dodanie użytkowania koncoli rcon żeby całą zawartość jej pokazywało a nie żeby tylko komendę wysyłała (widzenie całej calutkiej konsoli)

**Comment by Adexion** [comment]
Jest to praktycznie a wykonalne,
rCon jest połączeniem, które zwraca tylko odpowiedź do ostatniej wykonanej komendy, więc nie da się uzyskać za jego pomocą logów.

**Comment by Adexion** [comment]
W razie pojawienia się innych propozycji proszę o utworzenie nowego ticketa z propozycją rozwiązania problemu

**Comment by opiepl** [comment]
Otwieram ponownie. 
W innych panelach i na stronach hostingów przecież są normalnie wyświetlane całe konsole, dlaczego nie możemy zrobić tak jak oni?

**Comment by opiepl** [comment]
Zrobiłem research i wystarczy wczytywać po kolei ostatnie linie z pliku server.log. Chyba damy radę to ogarnąć. @Adexion

**Comment by likasop** [comment]
Okej to jak dacie rade to poproszę

pon., 6 gru 2021, 22:49 użytkownik opiepl ***@***.***>
napisał:

**Comment by Adexion** [comment]
Żeby to wykonać potrzebujemy udostępnienia przez serwer pliku serwer.log, który bez zmian po stronie VPS jest nie do odczytu.

**Comment by opiepl** [comment]
Potwierdzam, nie jest to możliwe na aktualnym etapie. Zamykam wątek.
