### ISSUE TITLE
Prośba o zakładkę bany

### ISSUE THREAD

**Issue by likasop** [Adexion/GameSitesSellIssue#7]
bany na podstawie rankingu nowa zakładka wszystko co związane z rankingiem zmienic na bany 

strona sfite.gamesites.pl

**Comment by opiepl** [comment]
Cześć @likasop, na pewno pojawi się taka funkcjonalność. Dodamy ją do naszych planów.

Pozdrawiam,
Michał Dyrka

**Comment by Adexion** [comment]
Funkcjonalność wprowadzona, na tą chwilę na stronie wyświetla się 20 ostatnich banów. W razie konieczności będzie to rozbudowywane
